### PR TITLE
InvalidCastException thrown when a store property is a value array such as byte[]

### PR DESCRIPTION
**Pull request by daveidmx**
When a store property is of a value array type such as `byte[]`, an `InvalidCastException` is thrown in `SerializerHelper` when casting `object input` to `object[]`. This is because arrays with value-typed elements are not covariant.

This change adds a generic handler type for serializing and deserializing arrays.

There's an opportunity to add support for byte arrays as base-64, but I didn't want to add that yet since it feels like a feature that should expose configuration options to control it, and that's a much bigger change than this simple bug fix.

I see you're currently working on a branch to add unit tests. Since there is no unit testing framework yet in main, I haven't added tests. I just did a simple save/load smoke test in Program using an entity type containing both a `byte[]` property and a property having a `ValueConverter` to `byte[]` (not included in the PR):

```
public class EntityWithArrayAndValueConverterToArray
{
    public int Id { get; set; }

    public byte[]? MyBytes { get; set; }

    public MyValueType MyValue { get; set; }
}

public record struct MyValueType(
    string StringValue);

internal sealed class MyValueConverter()
    : ValueConverter<MyValueType, byte[]>(
        modelValue => Encoding.UTF8.GetBytes(modelValue.StringValue),
        storeValue => new(Encoding.UTF8.GetString(storeValue)));

public class Context : DbContext
{
    public DbSet<EntityWithArrayAndValueConverterToArray> HasConversionEntities { get; set; }

    protected override void ConfigureConventions(ModelConfigurationBuilder configurationBuilder)
    {
        base.ConfigureConventions(configurationBuilder);

        configurationBuilder.Properties<MyValueType>()
            .HaveConversion<MyValueConverter>();
    }
}
```

### CODE REVIEW

**Comment by dualbios** [comment]
@daveidmx Many thanks for your efforts.
You have done a great job!
Unfortunately, I had published a new version with unit tests before saw your PR.
Would be good if you rebase your branch on the latest master and add some unit tests.

**Comment by daveidmx** [comment]
@dualbios I've added unit tests, and in the process I ran into the null-versus-empty issues you've referred to in #12. I'm going down the rabbit hole of making the `JsonSerializer` use the correct types per column. Before I go too far, I wanted to check if that's ok with you, or if you have significant work done on that front already.

**Comment by dualbios** [comment]
@daveidmx It is the next issue that I want to fix. I was waiting when you to merge your changes and did not start fixing it yet. If you fix this it would be so good.

**Comment by daveidmx** [comment]
I'm about halfway done rewriting `JsonSerializer` to use native JSON types, but I'm booked up for the rest of the day. I should be able to send an updated PR this weekend.

**Comment by daveidmx** [comment]
Superseded by #17

**Pull request closed without merging**
