### PR TITLE
Rewrite serializer to use native JSON types; fix byte array and null-versus-empty bugs

### PR DESCRIPTION
**Pull request by daveidmx**
This PR contains a couple discrete changes that I can break up if you prefer:
1. Add `*.lutconfig` to `.gitignore` to prevent checking in local live unit testing configuration.
2. Add `ContextTestClassBase`:
    * Boilerplate wire-up for a generically-defined `DbContext` type using `FileContextBase` with a `MockFileSystem`.
    * `SetupDb`, `TestDb`, and `AssertDb` instances to support test cases that need a fresh context to assert types are reloaded, etc.
    * Helpers for reading and writing JSON database files.
3. Lift the data filename extension from `FileBaseContextFileManager` to `ISerializer` to support plugging in different file formats in the future.
4. Rename `JsonDataSerializer` --> `JsonRowDataSerializer`; `ISerializer` --> `IRowDataSerializer` to help avoid type name conflicts with base types. (I noticed that the `JsonDataSerializer` filename `JsonSerializer` was already inconsistent, so I took the opportunity.)
5. Change the `ISerializer` (now `IRowDataSerializer`) interface to work with `Stream` rather than `string`.
6. Re-implement `JsonDataSerializer` (now `JsonRowDataSerializer`) to read and write native JSON types rather than always writing strings.
    * Fixed the null-versus-empty string round-tripping bug.
    * Naturally writes `byte[]` as base64, but supports reading from legacy CSV string as well as `JsonArray` of `JsonTokenType.Number`.
    * Should still read back files written by previous versions.

I've done cursory testing and added a handful of unit tests, but when I have more time later I can add more tests and do a quick perf check. But since this is a pretty big review I figure I'd get it in your hands ASAP.

Cheers,
David

### CODE REVIEW

**Comment by dualbios** [comment]
I am still reviewing the changes.
I added 2 small tests to check consistency.

My main question is, what is the purpose of using SetupDb, TestDb, and AssertDb? 
All these properties depend on FileSystem and 'must' have the same data. 
These properties depend on initialise order. If you initialise AssertDb before TestDb then tests fail.
Tell me more details about this.

Great job! Many thanks!
Konstantin.

**Comment by daveidmx** [comment]
> My main question is, what is the purpose of using SetupDb, TestDb, and AssertDb?
> All these properties depend on FileSystem and 'must' have the same data.

This may or may not be relevant for `FileContextBase`--I haven't looked closely yet at what's being kept in memory and will dig into that more--but for the SQL Server provider, consider this test:

```
var db = new MyDb();
db.Add(new Entity());
db.SaveChanges();

var entity = db.Entities.Single();
Assert(something about entity);
```

In this case the `entity` object will be the in-memory tracked entity created above, _not_ the entity as reloaded from storage, so it's not really testing anything valid about the persistence flow.

Using separate `DbContext` instances solves that:
```
TestDb.Add(new Entity());
TestDb.SaveChanges();

var entity = AssertDb.Entities.Single();
// entity has been freshly loaded from storage
```

I'm not married to the idea of presenting those 3 specific properties--the same thing could be accomplished with just a `CreateDbContext()` method:
```
using var testDb = CreateDbContext();
...
using var assertDb = CreateDbContext();
...
```

And as I mentioned, I'm not yet familiar with the `FileDbContext` behavior around concurrent contexts with the same backing storage. Your comment suggests to me that this is perhaps not yet supported  :D  so that is perhaps another area where we could add more tests and implement support in the future.

Does that make sense? Let me know your thoughts!

**Comment by daveidmx** [comment]
@dualbios I rewrote history (apologies in advance for making you rebase)
* The commits are cleaner and each one should be complete and make sense in isolation.
    * (I addressed all the comments I had left to myself.)
* I removed those 3 `XxxDb` properties in favor of just calling a `CreateDbContext()` method where appropriate in each test case.

**Comment by dualbios** [comment]
Hi @daveidmx!
Thanks for refactoring the commits. It is more readable.
Using `CreateDbContext `instead of 3 specific properties is better for understanding the code. 

I refactored the `TestDbContext `class because I am not able to build the solution with the last version of C#.
I pushed the commit with my changes to your branch. If you disagree let me know and delete the commit and I will make the changes in my branch.
Also, I added 2 simple tests.

You made a significant improvement. Your changes opened the door to my next improvement of the library. I want to add support for CSV files. I am thinking of it and thanks for your help!

If you agree with my changes let me know I will merge it to the master.

Cheers,
Konstantin

**Comment by daveidmx** [comment]
Looks good to me, though I'm surprised you had to change only that one file for C# 11.0. There are 5 more primary constructors and 56 collection expressions still in there. (I just locally added `<LangVersion>11.0</LangVersion>` to the projects to check.)

But hey, if this worked for you 🤷

**Comment by dualbios** [comment]
@daveidmx  you are right. it is a strange behaviour of MS VS for me. The editor shows me the errors but the compilator builds the solution.
I rolled back changes to primary constructors. Anyway, I need to switch to a new version of C# soon.
If you agree I will approve the PR.

**Comment by daveidmx** [comment]
Go for it! Thank you for taking the time to review this.

**Review by dualbios — APPROVED** [review]

**Pull request merged**
